"""Streamlit UI for arXiv Research Radar.

Run:  streamlit run app.py      (the FastAPI backend must be up at API_URL)
"""
import requests
import streamlit as st

import config

st.set_page_config(page_title="arXiv Research Radar", page_icon="📡", layout="wide")


def esc(text: str) -> str:
    """Stop Streamlit's markdown from treating $...$ as LaTeX (common in paper titles)."""
    return text.replace("$", r"\$")


def fmt_wait(seconds: int) -> str:
    if seconds < 90:
        return f"{seconds} seconds"
    if seconds < 5400:
        return f"about {round(seconds / 60)} minutes"
    return f"about {round(seconds / 3600)} hours"


@st.cache_data(ttl=300)
def load_papers() -> list[dict]:
    resp = requests.get(f"{config.API_URL}/papers", timeout=10)
    resp.raise_for_status()
    return resp.json()


def forwarded_headers() -> dict:
    """Relay the visitor's X-Forwarded-For to the API. Without this the API only sees
    this Streamlit server's address, so every visitor would share one rate-limit bucket."""
    try:
        xff = st.context.headers.get("X-Forwarded-For")
    except Exception:  # headers unavailable (e.g. some test/runtime contexts)
        xff = None
    return {"X-Forwarded-For": xff} if xff else {}


def error_body(resp: requests.Response) -> dict:
    try:
        body = resp.json()
        return body if isinstance(body, dict) else {}
    except ValueError:
        return {}


def show_answer(data: dict) -> None:
    st.markdown(esc(data["answer"]))
    if data.get("truncated"):
        st.caption("The answer hit the length limit and was cut off. Try a narrower question.")
    if data["cited_papers"]:
        st.subheader("Sources")
        for p in data["cited_papers"]:
            st.markdown(f"**[{p['id']}]** [{esc(p['title'])}]({p['url']}) · arXiv:{p['arxiv_id']}")


def ask(question: str) -> None:
    try:
        resp = requests.post(
            f"{config.API_URL}/ask",
            json={"question": question},
            headers=forwarded_headers(),
            timeout=100,  # the API itself allows up to ~30s per LLM attempt, with retries
        )
    except requests.Timeout:
        st.error("That took too long. Please try again.")
        return
    except requests.RequestException:
        st.error("Can't reach the server right now. Please try again in a bit.")
        return

    if resp.status_code == 200:
        show_answer(resp.json())
        return

    body = error_body(resp)
    detail = body.get("detail") if isinstance(body.get("detail"), str) else None
    if resp.status_code == 429 and body.get("error") == "daily_cap":
        st.info(f"🌙 {detail or 'Demo limit reached, please try again tomorrow.'}")
    elif resp.status_code == 429:
        wait = body.get("retry_after_seconds")
        wait_text = f" You can ask again in {fmt_wait(wait)}." if wait else ""
        st.warning(f"⏳ {detail or 'Too many questions.'}" + wait_text)
    else:
        st.error(detail or "Something went wrong. Please try again.")


# ---------- sidebar ----------
with st.sidebar:
    st.header("Indexed papers")
    try:
        papers = load_papers()
    except requests.RequestException:
        papers = []
        st.error("Couldn't load the paper list (backend unreachable).")
    if papers:
        st.caption(f"{len(papers)} most recent arXiv papers on the topic, refreshed weekly.")
        for p in papers:
            authors = ", ".join(p["authors"][:2]) + (" et al." if len(p["authors"]) > 2 else "")
            st.markdown(f"[{esc(p['title'])}]({p['abs_url']})  \n<small>{authors} · {p['published'][:10]}</small>",
                        unsafe_allow_html=True)
    st.divider()
    st.caption(
        f"Demo limits: {config.ASK_RATE_LIMIT.replace('/', ' questions per ')} per visitor, "
        f"{config.DAILY_CAP} questions per day in total."
    )

# ---------- main ----------
st.title("📡 arXiv Research Radar")
st.write("Ask a question and get an answer grounded in the latest papers, with citations. "
         "Answers use only the indexed papers listed in the sidebar.")

with st.form("ask_form"):
    question = st.text_input(
        "Your question",
        max_chars=config.MAX_QUESTION_CHARS,
        placeholder="e.g. What defenses exist against corpus poisoning in RAG?",
    )
    submitted = st.form_submit_button("Ask")

if config.LLM_PROVIDER == "gemini":
    # Google's free-tier terms allow using and human-reviewing submitted content: tell visitors.
    st.caption("Answers are generated by Google's Gemini API (free tier). Google may use and review "
               "submitted questions, so please don't enter personal or sensitive information.")

if submitted:
    question = question.strip()
    if len(question) < 3:
        st.warning("Please type a question (at least 3 characters).")
    else:
        with st.spinner("Searching the papers and writing an answer..."):
            ask(question)
